Updated Readme
coding-geek21/classDeck pull request #64
Opened 2022-03-10 13:57 UTC by ayush-sleeping

## Related Issue or bug
  - Updated Readme

Fixes: #[ Readme Update #63 ]

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## How Has This Been Tested?

For Final Output Visit here : https://github.com/ayush-sleeping/classDeck/blob/develop/README.md

## Checklist:

- [x] Have you checked there aren't other open Pull Requests for the same update/change?
- [x] My submission doesn't break any existing feature.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

# 
# 

Hey maintainer , Checkout this PR and if all things are good to go , Kindly merge it ..........

2022-03-10 16:42 UTC, coding-geek21 requested changes

2022-03-10 16:42 UTC, coding-geek21 commented on README.md
> +    <a href="https://classdeck.herokuapp.com/"><strong>ZeroOctave Official site »</strong></a>
Change it to ClassDeck Official site

2022-03-10 16:42 UTC, coding-geek21 commented on README.md
> +<h1 align="center"> ClassDeck </h1>
Can you add the ClassDeck logo before the heading?
Link :  https://github.com/coding-geek21/classDeck/blob/develop/classDeck/static/img/logo.png

2022-03-11 05:10 UTC, ayush-sleeping commented on README.md
> +<h1 align="center"> ClassDeck </h1>
I am in College now , When I will reach home in the evening, I will complete this task....

2022-03-11 10:35 UTC, ayush-sleeping commented
hey @coding-geek21 , Checkout now, 
 https://github.com/ayush-sleeping/classDeck/blob/develop/README.md

2022-03-11 14:04 UTC, merged